### ISSUE TITLE
Run on custom IP

### ISSUE THREAD

**Issue by dsoronda** [TheCodeCleaner/MicroService4Net#1]
Currently service uses Port as parameter and it binds itself on http://localhost:{port}.

This creates problem on Windows 10 because it requires Administrators rights to run properly, otherwise application starts and nobody can't connect to it.

Also, when starting application, code throws exception on  that is misguiding : 

One or more errors occurred.
Service {myApplication} started on port 12345
Press any key to exit...

This is in from Microsevice.Start method:
    this._selfHostServer = new SelfHostServer("http://localhost:" + this._port, true); <-- hardcoded IP
    this._selfHostServer.Connect(); <-- this throws exception that is just logged and not re-throw back

I tested it on version 1.

**Comment by dsoronda** [comment]
As I see, this is fixed in latest release so I'll close this issue.

**Comment by dsoronda** [comment]
Actually, this is still an issue :

``` csharp
 public SelfHostServer(int port, bool callControllersStaticConstractorsOnInit = true)
        {
            _options = new StartOptions("http://*:" + port); // this binds to all IPs and it may be security issue (VPNs etc)
```

Quickfix solution could be :

``` csharp
public SelfHostServer(string ipAddress = "localhost" , int port = 80, bool callControllersStaticConstractorsOnInit = true)
{
            _options = new StartOptions($"http://{ipAddress}:{port}");
```

**Comment by TheCodeCleaner** [comment]
Why you need to check the _isValidUri? I can always use new SelfHostServer(_ipAddress, _port).
